-- SELECT 연습문제 ***********************************************\
--1
SELECT EMP_ID 사번, EMP_NAME 이름, JOB_ID 직급코드, DEPT_ID 부서코드, SALARY 급여
FROM EMPLOYEE
WHERE JOB_ID = 'J2' AND DEPT_ID = '90';
--2
SELECT EMP_ID, EMP_NAME, MGR_ID, BONUS_PCT 
FROM EMPLOYEE 
WHERE HIRE_DATE >= '82/01/01' OR JOB_ID = 'J3';
--3
SELECT EMP_ID 사번, EMP_NAME 사원명, JOB_ID 직급코드, (SALARY + SALARY * NVL(BONUS_PCT,0))*12 "연봉(원)"
FROM EMPLOYEE
WHERE JOB_ID <> 'J4'
ORDER BY JOB_ID;

--4
SELECT EMP_ID, EMP_NAME, EMAIL, SALARY, BONUS_PCT

FROM EMPLOYEE
WHERE BONUS_PCT BETWEEN 0.1 AND 0.2;


--5
SELECT EMP_ID, EMP_NAME, BONUS_PCT, SALARY, HIRE_DATE
FROM EMPLOYEE
WHERE NOT BONUS_PCT BETWEEN 0.1 AND 0.2;

--6
SELECT EMP_NAME, BONUS_PCT, SALARY
FROM EMPLOYEE
WHERE HIRE_DATE >= '82/01/01';

--7
SELECT EMP_ID, EMP_NAME, BONUS_PCT, PHONE
FROM EMPLOYEE
WHERE BONUS_PCT IN (0.1, 0.2);

--8
SELECT EMP_ID, EMP_NAME, BONUS_PCT, EMP_NO
FROM EMPLOYEE
WHERE BONUS_PCT NOT IN (0.1, 0.2) OR BONUS_PCT IS NULL;

--9
SELECT EMP_ID, EMP_NAME, HIRE_DATE
FROM EMPLOYEE
WHERE EMP_NAME LIKE '이%'
ORDER BY HIRE_DATE;

--10
SELECT EMP_ID, EMP_NAME, EMP_NO, SALARY
FROM EMPLOYEE
WHERE EMP_NO LIKE '_______2%'
ORDER BY 4 DESC;